version: "3.6"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "/usr/src/app"
  db:
    image: mysql:8.3.0
    environment:
      # MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_app_development
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - ./tmp/db:/var/lib/mysql